"""Add course column to student

Revision ID: 29de3279a6a7
Revises: e9c2c207f486
Create Date: 2026-01-22 15:28:55.635173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29de3279a6a7'
down_revision = 'e9c2c207f486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=50), nullable=False, server_default='Unknown'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###
